### PR TITLE
fix(pkg/rke2): psa custom path

### PR DESCRIPTION
**Pull request by perriea**
#### Proposed Changes ####

In fact, a `pod-security-admission-config-file` flag exists to define an arbitrary path for the PSA. But even if the flag is set, the file is still created at `/etc/rancher/rke2/rke2-pss.yaml` (`defaultPSAConfigFile`). This is incorrect behavior.

#### Types of Changes ####

Bugfix

#### Linked Issues ####

/!\ This flag isn't registered in the documentation #3440

### CODE REVIEW

**Comment by perriea** [comment]
Anyone is available to review this ?

**Comment by brandond** [comment]
I believe this was intended behavior - we only write the default config file. If you provide your own config file path, it will be used, but you are responsible for populating it with the correct content. I would defer to @galal-hussein on that though.

**Comment by brandond** [comment]
To be clear @perriea - you object to the fact that RKE2 is writing the default configuration file out to the fixed location, even if you've specified a custom path that already contains your desired configuration?

**Comment by perriea** [comment]
Yes, otherwise I don't understand the existence of this flag which at this moment is useless 😅

**Comment by erikfuego** [comment]
Correct me if i'm wrong @perriea, but I think the point of this flag is for us to provide our own version of the `admission-control-config.yaml` right? Which is why the path stays the same on the node

**Pull request closed without merging**
