### PR TITLE
Update Cilium to v1.14.5

### PR DESCRIPTION
**Pull request by mgfritch**
Also provides an update for:

* hardened-cni-plugins 1.4.0-build20240122
* cilium-envoy v1.26.6-ad82c7c56e88989992fd25d8d67747de865c823b

Linked Issue: https://github.com/rancher/rke2/issues/5155
Linked Issue: https://github.com/rancher/rke2/issues/5333

### CODE REVIEW

**Comment by manuelbuil** [comment]
we are still on code freeze, so we can't merge

**Review by manuelbuil — APPROVED** [review]

**Comment by brandond** [comment]
Users are already asking about v1.15.0 😵‍💫

**Comment by rbrtbnfgl** [comment]
But it was released yesterday 😅

**Comment by brandond** [comment]
That's what I said!

**Comment by manuelbuil** [comment]
I think we should release Cilium v1.15 in the February release (if we ever unfreeze)

**Comment by mgfritch** [comment]
I'm happy to do another version bump to cilium v1.15.0.
I've created issue https://github.com/rancher/rke2/issues/5354 to track the progress into a future release

**Comment by mgfritch** [comment]
closed in favor of https://github.com/rancher/rke2/pull/5420

**Pull request closed without merging**
