### PR TITLE
Bump harvester-cloud-provider v0.2.4

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
#### Proposed Changes ####

Update the Harvester cloud provider version

#### Types of Changes ####

bump newer version

#### Verification ####

Regular tests for harvester-cloud-provider

#### User-Facing Change ####

```release-note
Bump Harvester-cloud-provider v0.2.4
```

### CODE REVIEW

**Comment by brandond** [comment]
Current CI failures are due to a recently merged PR, I'll fix that tomorrow and you can rebase.

**Comment by Vicente-Cheng** [comment]
> Current CI failures are due to a recently merged PR, I'll fix that tomorrow and you can rebase.

Sure, thanks @brandond

**Review by manuelbuil — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
needs rebase

**Comment by Vicente-Cheng** [comment]
> needs rebase

Thanks @brandond,
rebased this PR and all backport PRs

Please help to review!

**Review by brandond — APPROVED** [review]

**Pull request merged**
