### PR TITLE
update systemd service files to include type notify

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <brian.downs@gmail.com>

#### Proposed Changes ####

Update type to be notify so that systemd will only be notified of rke2 being up when it writes to the systemd notify socket.

#### Linked Issues ####

#989

### CODE REVIEW

**Review by Oats87 — APPROVED** [review]
This LGTM; however, is this going to cause a change in behavior for our users where `systemctl start rke2-server` is going to start hanging for a decent period of time?

**Comment by briandowns** [comment]
@Oats87 This does change the expected behavior. On server startup, it will wait until the server (supervisor components) is up and running and will do so for the agent as well but will require a little reworking of the k3s agent code to do so. I'm currently working on the agent code now.

**Comment by brandond** [comment]
Is this safe to merge without the agent code merged yet, or will it just hang on startup?

**Comment by briandowns** [comment]
No hangs as far as I noticed in testing.

**Review by brandond — APPROVED** [review]

**Pull request merged**
