### PR TITLE
Activate systemd with tarball installation

### PR DESCRIPTION
**Pull request by zaggash**
#### Proposed Changes ####

Edit documentation about Tarball systemd activation

#### Types of Changes ####

Quickstart page modification about systemd enablement.

### CODE REVIEW

**Comment by brandond** [comment]
This shouldn't be necessary. What distro are you on that doesn't search for units in /usr/local/lib/systemd/system?

**Comment by zaggash** [comment]
Default Ubuntu `ubuntu-18-04-x64` from DigitalOcean.

Using the quickstart command up to the `systemctl enable` where is says there is no such unit file.

**Comment by brandond** [comment]
Hmm, on my Ubuntu systems this is a valid path:

```
(python38) brandond@seago:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

(python38) brandond@seago:~$ man systemd | grep -A4 'System unit directories'
       System unit directories
           The systemd system manager reads unit configuration from various directories. Packages that want to install unit files shall place them in the
           directory returned by pkg-config systemd --variable=systemdsystemunitdir. Other directories checked are /usr/local/lib/systemd/system and
           /lib/systemd/system. User configuration always takes precedence.  pkg-config systemd --variable=systemdsystemconfdir returns the path of the system
           configuration directory. Packages should alter the content of these directories only with the enable and disable commands of the systemctl(1) tool.
```

**Comment by zaggash** [comment]
I just tried to reproduce the issue twice and I can't.
Maybe my previous node was broken.

Sorry for the noise.

**Pull request closed without merging**
