### PR TITLE
Add stable channel to rke2-channelserver and set v1.18.12+rke2r1 as stable

### PR DESCRIPTION
**Pull request by MonzElmasry**
#### Linked Issues ####

https://github.com/rancher/rke2/issues/404

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by dweomer — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by davidnuzik** [comment]
This needs to wait to be merged until the release is out and we are satisfied with marking this as stable.

**Comment by davidnuzik** [comment]
Update: We are going to wait until our planned early November release. The release should contain etcd improvements. After v1.18.10+rke2r2 is out and we are satisficed with the stability (we may wait 3-7 days until post release) we will then mark it as stable. 
The PR will need updating to +rke2r2 release later, although keep in mind it's possible we may decide to delay release until at least 11/11 to pickup upstream patch bump.

**Comment by davidnuzik** [comment]
Since we pushed out date to 11/11 - we shall also be picking up upstream v1.18.11 and thus our expected version to promote to stable should be `v1.18.11+rke2r1`

**Comment by davidnuzik** [comment]
@MonzElmasry as low priority, can you update this to .12 patch? Then, 11/23 we can merge this in (1 week post release, per process). Assuming no serious bugs come in for RKE2.

**Pull request merged**
