### PR TITLE
Fix aws s3 artifact upload issues

### PR DESCRIPTION
**Pull request by ivan-claire**
#### Proposed Changes ####

Fixing `aws s3 cp`  command which uploads one artifact at a time and does not recognise regex (uses --include and exclude filters). 
Also, updating  AWS creds to match drone secrets and passing them through dapper.

#### Types of Changes ####
ci bugfix

#### Verification ####

Check CI logs

#### Linked Issues ####
#6569

### CODE REVIEW

**Comment by manuelbuil** [comment]
Is this what causes rke2 deployment to fail when deploying from Commit? I get:
```
[INFO]  downloading airgap checksums at https://rke2-ci-builds.s3.amazonaws.com/rke2-images.linux-amd64-6a0dd2b5b44fecac6d6fc757c430bae2c16666fa.tar.gz.sha256sum

curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by ivan-claire** [comment]
> Is this what causes rke2 deployment to fail when deploying from Commit? I get:
> 
> ```
> [INFO]  downloading airgap checksums at https://rke2-ci-builds.s3.amazonaws.com/rke2-images.linux-amd64-6a0dd2b5b44fecac6d6fc757c430bae2c16666fa.tar.gz.sha256sum
> 
> curl: (22) The requested URL returned error: 404 Not Found
> ```

This is very likely the cause of the issue.
I can't find the `rke2-images.linux-amd64-6a0dd2b5b44fecac6d6fc757c430bae2c16666fa.tar.gz.sha256sum` object in the s3 bucket. Implying that the object was not uploaded, which is what this pr seeks to resolve.

**Comment by ivan-claire** [comment]
The files are succesfully being uploaded to s3 and the policy for downloading the objects has been set.
Screenshot 2022-11-29 at 16 22 30

**Review by brandond — APPROVED** [review]

**Comment by mdrahman-suse** [comment]
Hi rke2 still seems to be having issues, has this been resolved?
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=689fb9fc9ec6840a94536a807b18ef653558dd88 sh -
[INFO]  using commit 689fb9fc9ec6840a94536a807b18ef653558dd88 as release
[INFO]  downloading airgap checksums at https://rke2-ci-builds.s3.amazonaws.com/rke2-images.linux-amd64-689fb9fc9ec6840a94536a807b18ef653558dd88.tar.gz.sha256sum
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by ivan-claire** [comment]
> Hi rke2 still seems to be having issues, has this been resolved?
> 
> ```
> curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=689fb9fc9ec6840a94536a807b18ef653558dd88 sh -
> [INFO]  using commit 689fb9fc9ec6840a94536a807b18ef653558dd88 as release
> [INFO]  downloading airgap checksums at https://rke2-ci-builds.s3.amazonaws.com/rke2-images.linux-amd64-689fb9fc9ec6840a94536a807b18ef653558dd88.tar.gz.sha256sum
> curl: (22) The requested URL returned error: 404 Not Found
> ```

hmmm, where do you get the error? Is your code or environment up to date with the changes from this pr?
According to the CI build for this pr, the sha256sum files are being uploaded to the buckets and I can see these files in the s3 bucket.

```
aws s3 cp /tmp/tmp.QQ5pI2nlal/rke2.linux-amd64-e9d319ab591c410b8daebe5e35d900225fef5922.tar.gz.sha256sum s3://rke2-ci-builds
Completed 90 Bytes/90 Bytes (1.4 KiB/s) with 1 file(s) remaining
upload: ../tmp/tmp.QQ5pI2nlal/rke2.linux-amd64-e9d319ab591c410b8daebe5e35d900225fef5922.tar.gz.sha256sum to s3://rke2-ci-builds/rke2.linux-amd64-e9d319ab591c410b8daebe5e35d900225fef5922.tar.gz.sha256sum
```

**Comment by rohitsakala** [comment]
Also, there are no files with this pattern in the google cloud bucket `rke-ci-builds` 

rke2-images.linux-amd64-${COMMIT}.tar.gz.sha256sum

There are files with this pattern  (notice the word "images" missing)

rke2.linux-amd64-${COMMIT}.tar.gz.sha256sum

and it makes sense from these scripts

https://github.com/rancher/rke2/blob/master/scripts/dev-runtime-image#L15
https://github.com/rancher/rke2/blob/master/scripts/build-upload#L41

**Comment by caroline-suse-rancher** [comment]
@ivan-claire was there a separate issue for this, or should it just be linked to #3595 ?

**Comment by ivan-claire** [comment]
@caroline-suse-rancher thanks for pointing that out. I just linked the issue.

**Pull request merged**
