### PR TITLE
cilium: Update to 1.9.8

### PR DESCRIPTION
**Pull request by mrostecki**
Update Cilium from 1.9.6 to 1.9.8. Changelogs of the last two releases:

* https://github.com/cilium/cilium/releases/tag/v1.9.8
* https://github.com/cilium/cilium/releases/tag/v1.9.7

Fixes: #1099
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

#### Proposed Changes ####

Update of Cilium to 1.9.8

#### Types of Changes ####

New CNI plugin version

#### Verification ####

* By deploying rke2 with `--cni=cilium` and ensuring that the cluster is functional
* By performing an upgrade of Cilium on already existing rke2 cluster

#### Linked Issues ####

#1099

### CODE REVIEW

**Comment by manuelbuil** [comment]
Cilium gets deployed through the helm chart in rke2-charts. You should also update the tarball there https://github.com/rancher/rke2-charts/blob/main-source/packages/cilium/package.yaml#L1 and then change the helm chart version in the Dockerfile file in this rke2 repo

**Comment by mrostecki** [comment]
I have a PR to rke2-charts - https://github.com/rancher/rke2-charts/pull/100 - is there anything missing in it?

Thanks for pointing out that I have to update the Dockerfile too.

**Comment by mrostecki** [comment]
Marking it as a draft before https://github.com/rancher/rke2-charts/pull/100 https://github.com/rancher/image-mirror/pull/120 get in

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Image bump looks good - will re-review once you get the chart updated in the Dockerfile.

**Review by brandond — APPROVED** [review]

**Review by manuelbuil — APPROVED** [review]

**Pull request merged**
