### PR TITLE
Bump K3s and component versions

### PR DESCRIPTION
**Pull request by brandond**
#### Proposed Changes ####

* Bump K3s to track with upstream master branch.
  Updates k3s: https://github.com/k3s-io/k3s/compare/13c633da1268...614da78e43646dfc5b6fa4bbaab6078da7c18597
* Bump golang/containerd/sonobuoy/golangci-lint versions

#### Types of Changes ####

version bump

#### Verification ####

Check component versions

#### Linked Issues ####

* tbd cut-release issue

### CODE REVIEW

**Comment by manuelbuil** [comment]
Could you include today's k3s PRs? I need the one removing the windows stuff from k3s for my rke2 windows refactoring PR

**Comment by brandond** [comment]
I am waiting for @dereknola to add the bundled binary flag to the k3s agent and then I'll update again.

**Review by dereknola — APPROVED** [review]

**Comment by brandond** [comment]
@manuelbuil you should be set to rebase your PR.

**Comment by manuelbuil** [comment]
@brandond will you update k3s version in release-1.24 and release-1.23?

**Comment by brandond** [comment]
@manuelbuil yes, I was planning on doing backports next week .

**Pull request merged**
