### PR TITLE
update link to known issues network manager

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <brian.downs@gmail.com>

#### Proposed Changes ####

Updates the version of mkdocs in the Dockerfile to be 7.1.7 which is the version before "latest".

#### Linked Issues ####

#1164

### CODE REVIEW

**Review by Oats87 — DISMISSED** [review]
This shouldn't be necessary -- the links all worked before. Did something change in the way we publish our docs that broke these links? The link right above this one is also broken.

**Comment by briandowns** [comment]
Not aware of any changes but updated the other broken link as well.

**Review by brandond — APPROVED** [review]

**Comment by briandowns** [comment]
This issue seems to be related to the latest release of mkdocs, 7.1.8. I've put the previous, working version tag in the Dockerfile that generates the docs.

**Comment by brandond** [comment]
Looks like the mkdocs version bump is the culprit:
```
brandond@dev01:~$ docker run --rm -it squidfunk/mkdocs-material:7.1.7 --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
brandond@dev01:~$ docker run --rm -it squidfunk/mkdocs-material:7.1.8 --version
mkdocs, version 1.2.1 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
```

https://www.mkdocs.org/about/release-notes/#version-12-2021-06-04
Specifically:
> The use_directory_urls configuration option will be forced to false if site_url is set to an emtpy string. In that case, if use_directory_urls is not explicitly set to false, a warning will be issued (https://github.com/mkdocs/mkdocs/issues/2189).

Rather than downgrading, you might try just setting `use_directory_urls: true` and see if it gets the old behavior.

**Comment by briandowns** [comment]
My intent was to bring this back to the expected version and behavior and evaluate how we wanted to move forward whether it be this additional change or update the links themselves.

**Review by brandond — APPROVED** [review]

**Review by Oats87 — APPROVED** [review]

**Pull request merged**
