### PR TITLE
Add flannel CNI plugin

### PR DESCRIPTION
**Pull request by manuelbuil**
#### Proposed Changes ####

This PR adds flannel CNI plugin as an option for rke2. The reasoning is covered in the adr: https://github.com/rancher/rke2/pull/5145

Please only review the commit [Add CNI plugin flannel support for Windows](https://github.com/rancher/rke2/pull/5322/commits/f62faa4da342dddb7bb917a8e80195c0c9c54e5f). The other one is covered in the PR: https://github.com/rancher/rke2/pull/5276, which abstracts the interface so that more CNI plugins can be used

#### Types of Changes ####

New feature

#### Verification ####

Use `cni: flannel` when deploying rke2

#### Linked Issues ####

https://github.com/rancher/rke2/issues/5215

#### User-Facing Change ####

```release-note
Flannel added as CNI plugin option
```

### CODE REVIEW

**Comment by dereknola** [comment]
Does this build on https://github.com/rancher/rke2/pull/5276?

**Comment by manuelbuil** [comment]
> Does this build on #5276?

Yes! There are two commits in this PR. One is #5276. I can't merge it yet because of code freeze. Once I merge it, this PR will only have one commit. I probably should write that in the description

**Comment by brandond** [comment]
GitHub doesn't have proper support for stacked PRs yet, unfortunately... so the best you can do is just call out in the comments that it's depending on another PR:

> * [ ] Blocked on https://github.com/rancher/rke2/pull/5276

**Review by thomasferrandiz — APPROVED** [review]

**Review by dereknola — APPROVED** [review]

**Comment by manuelbuil** [comment]
This PR should be tested together with https://github.com/rancher/rke2/pull/5421 which fixes a few minor issues

**Pull request merged**
