### PR TITLE
Revert "Add Adminstrator check to windows install.ps1"

### PR DESCRIPTION
**Pull request by dereknola**
Strong push-back from the windows rke2 team has necessitated reverting rancher/rke2#2346.

### CODE REVIEW

**Comment by luthermonson** [comment]
asking derek to revert this commit, the #requires feature in powershell is a comment, it's not guaranteed to actually check anything if ran via some powershell scripting IDE etc. the standard way to guarantee the admin check is exactly how we have it in the script and will even function in powershell core.

**Review by luthermonson — APPROVED** [review]

**Comment by brandond** [comment]
Can we do both? Put the code check back in for IDEs, but leave the `#requires` in for folks running it directly from the shell? Does having it in hurt anything?

**Review by rosskirkpat — APPROVED** [review]

**Comment by luthermonson** [comment]
if you want to leave a comment in a script i wont stop you... but it's pointless with the real checks already happening. the original issue for this is already determined to be an error in the vagrant scripts. i dont see why this needs to be discussed further

**Comment by brandond** [comment]
Just trying to learn something, sorry. I didn't block merging with my review :shrug:

**Comment by brandond** [comment]
For the record, https://github.com/rancher/rke2/issues/2345 was caused by copying install.sh into the Windows vagrant host as install.ps1; there was not anything wrong with install.ps1 itself to necessitate the change, regardless of whether or not the `#requires` check is useful.

**Pull request merged**
