### PR TITLE
Update to v1.24.10

### PR DESCRIPTION
**Pull request by briandowns**
Signed-off-by: Brian Downs <brian.downs@gmail.com>

### CODE REVIEW

**Comment by brooksn** [comment]
Should this also be updating to hardened-kubernetes 1.24.10?

**Comment by briandowns** [comment]
> Should this also be updating to hardened-kubernetes 1.24.10?

It does in all but one place. Nice spot. Thank you.

**Review by cwayne18 — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
Still seeing `FROM rancher/hardened-kubernetes:v1.24.9-rke2r2-build20230104 AS kubernetes` in the Dockerfile

**Comment by briandowns** [comment]
> Still seeing `FROM rancher/hardened-kubernetes:v1.24.9-rke2r2-build20230104 AS kubernetes` in the Dockerfile

Laptop dropped network on the push.

**Review by galal-hussein — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Pull request merged**
