### PR TITLE
Bump multus, cilium and flannel version

### PR DESCRIPTION
**Pull request by manuelbuil**
#### Proposed Changes ####

Bump multus, cilium and flannel charts so that we use the latest version of cni-plugins.

Flannel version includes windows and linux

#### Types of Changes ####

Version bump

#### Verification ####

Deploy those CNIs and verify that things are still working:
* Cilium
* Multus (with whatever other CNI plugin)
* Flannel in both windows and linux

#### Linked Issues ####

https://github.com/rancher/rke2/issues/7090

#### User-Facing Change ####

```release-note

```

### CODE REVIEW

**Review by dereknola — APPROVED** [review]

**Review by thomasferrandiz — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by manuelbuil** [comment]
On hold, waiting for @brooksn to explain this PR: https://github.com/rancher/rke2-charts/pull/548. Maybe he found problems in the new version?

**Comment by cwayne18** [comment]
@manuelbuil is this to fix a specific CVE or is this just generally a "good hygiene" bump

**Comment by manuelbuil** [comment]
> @manuelbuil is this to fix a specific CVE or is this just generally a "good hygiene" bump

a "good hygiene" bump

**Review by thomasferrandiz — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Review by thomasferrandiz — APPROVED** [review]

**Pull request merged**
