### PR TITLE
Upgrade kube-proxy version

### PR DESCRIPTION
**Pull request by manuelbuil**
This new image fixes the bug described in https://github.com/rancher/rke2/issues/1229

Signed-off-by: manuel <mbuill@suse.com>

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by manuelbuil** [comment]
I'm going to add the kube-proxy helm update here too. Give me a couple of minutes

**Comment by manuelbuil** [comment]
It should be ready now

**Review by briandowns — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]

**Comment by manuelbuil** [comment]
CI fails due to https://github.com/rancher/rke2/issues/1301:
```
[[36mBASICS[m] E0714 19:35:14.823732       1 server.go:587] healthz server failed: failed to start proxier healthz on 127.0.0.1:10256: listen tcp 127.0.0.1:10256: bind: address already in use
```
Waiting for a PR to fix it

**Review by brandond — APPROVED** [review]

**Comment by manuelbuil** [comment]
This PR on top of Luther's PR https://github.com/rancher/rke2/pull/1381 works in CI. As soon as it merges, we will be able to merge this one too

**Comment by manuelbuil** [comment]
> # [Codecov](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher) Report
> 
> > Merging [#1303](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher) ([505e7f8](https://github.com/rancher/rke2/commit/505e7f85bf97339e45c96d40ccc21033b7b7818b)) into [master](https://codecov.io/gh/rancher/rke2/commit/1e52187196784aa9f6b8efabb49525873e47d69f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher) ([1e52187](https://github.com/rancher/rke2/commit/1e52187196784aa9f6b8efabb49525873e47d69f)) will **not change** coverage.
> > The diff coverage is `n/a`.
> 
> [Impacted file tree graph](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher)
> 
> ```diff
> @@          Coverage Diff           @@
> ##           master   #1303   +/-   ##
> ======================================
>   Coverage    8.52%   8.52%           
> ======================================
>   Files          20      20           
>   Lines        1690    1690           
> ======================================
>   Hits          144     144           
>   Misses       1524    1524           
>   Partials       22      22           
> ```
> 
> Flag 	Coverage Δ 	
> unittests 	`8.52% <ø> (ø)` 	
> 
> Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher#carryforward-flags-in-the-pull-request-comment) to find out more.
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher). Last update [1e52187...505e7f8](https://codecov.io/gh/rancher/rke2/pull/1303?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rancher).

wow!!!! Cool! kudos @dereknola

**Pull request merged**
