### PR TITLE
Bump k3s version

### PR DESCRIPTION
**Pull request by galal-hussein**

### CODE REVIEW

**Comment by brandond** [comment]
There's a lot here, do we have a tracking issue that calls these out for QA?
https://github.com/k3s-io/k3s/compare/238dc2086e94...9859ec7a8158

**Comment by galal-hussein** [comment]
I dont know if we need to create separate issues for this, can this be part of the effort on https://github.com/rancher/rke2/issues/1231

> There's a lot here, do we have a tracking issue that calls these out for QA?
> [k3s-io/k3s@238dc20...9859ec7](https://github.com/k3s-io/k3s/compare/238dc2086e94...9859ec7a8158)

**Comment by brandond** [comment]
I believe we agreed in the past that any features or bugfixes that get pulled into RKE2 via K3s bump need a tracking issue in the RKE2 repo so that QA knows what to test. I personally would be OK with a single issue in RKE2 that links to all the K3s issues closed by commits in that range - but QA needs some sort of concrete list to work off of that doesn't require them just clicking through the commit log and trying to figure it out for themselves.

**Comment by galal-hussein** [comment]
> I believe we agreed in the past that any features or bugfixes that get pulled into RKE2 via K3s bump need a tracking issue in the RKE2 repo so that QA knows what to test. I personally would be OK with a single issue in RKE2 that links to all the K3s issues closed by commits in that range - but QA needs some sort of concrete list to work off of that doesn't require them just clicking through the commit log and trying to figure it out for themselves.

got it, will create an issue, and closing this PR for now and openning a new one with the right k3s pull

**Pull request closed without merging**
