### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by daxmc99**
Fixes broken FIPS link

### CODE REVIEW

**Comment by cjellick** [comment]
hi dax! thanks for the pr, but this links appears to be working for me.

**Comment by daxmc99** [comment]
Hi! :) 

https://github.com/rancher/rke2/blob/master/security/fips_support.md returns a `404` for me. 
Not sure if my suggestion is the correct page though.

**Comment by cjellick** [comment]
Hrm. Whether I click it form docs.rke2.io or from https://github.com/rancher/rke2/blob/master/docs/index.md, the link resolves apporpriately. How/where are you clicking it and having it 404?

I do agree that `https://github.com/rancher/rke2/blob/master/security/fips_support.md` does not resolve, but thats not the link in either of those cases. 
Screen Shot 2020-10-27 at 4 21 55 PM

**Comment by brandond** [comment]
@cjellick it's broken in the README, which is what the pr is for.
https://github.com/rancher/rke2/blob/master/README.md

**Review by brandond — APPROVED** [review]

**Comment by cjellick** [comment]
Oi vey.
🥴🤦🏻

**Review by briandowns — APPROVED** [review]

**Pull request merged**
