### PR TITLE
bump containerd to 1.5.10, remove wins and flannel

### PR DESCRIPTION
**Pull request by rosskirkpat**
https://github.com/rancher/rke2/issues/2575

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by phillipsj — APPROVED** [review]
LGTM!

**Comment by briandowns** [comment]
Is this needed or intended to go out in the r2 release we're working on? If not, can you revert the merge? We'll be updating containerd in k3s and here but in k3s will be going out in the patch release next week.

**Comment by rosskirkpat** [comment]
> Is this needed or intended to go out in the r2 release we're working on? If not, can you revert the merge? We'll be updating containerd in k3s and here but in k3s will be going out in the patch release next week.

I thought the r2 release was going to have cherry picked commits off of the r1 tag, which was why I merged.

**Comment by briandowns** [comment]
No, it was decided that wouldn't be the case.

**Pull request merged**
