### PR TITLE
Update sriov images to `v1.3.0`

### PR DESCRIPTION
**Pull request by mgfritch**
Also updates node-feature-discovery to `0.15.6`
Issue: https://github.com/rancher/rke2/issues/6705

Chart releases:
- SUSE Edge: https://github.com/suse-edge/charts/pull/145
- Rancher: https://github.com/rancher/charts/pull/4394

### CODE REVIEW

**Review by thomasferrandiz — APPROVED** [review]

**Review by brandond — CHANGES_REQUESTED** [review]
Where's the corresponding chart bump? Just bumping the images in the tarball doesn't change what the chart uses.

**Comment by mgfritch** [comment]
> Where's the corresponding chart bump? Just bumping the images in the tarball doesn't change what the chart uses.

The SR-IOV chart is currently maintained in the SUSE edge repo and we've added a [deprecation warning](https://github.com/rancher/charts/pull/4025) for it in the rancher chart repo.

- SUSE edge: https://github.com/suse-edge/charts/pull/145
- Rancher Charts: https://github.com/rancher/charts/pull/4394

**Comment by brandond** [comment]
OK but how do we ensure that the images included in the airgap tarball are the same ones referenced by the chart? Do the RKE2 docs need to cover what specific version of the SR-IOV chart its airgap images are valid with? What versions of the chart are these NEW images valid with? I see that https://docs.rke2.io/networking/multus_sriov#using-multus-with-sr-iov just points to rancher charts, but it doesn't tell you what version of the chart to deploy.

**Comment by rbrtbnfgl** [comment]
I think we can't. SR-IOV chart is installed through helm and it's not associated to the specific RKE2 version. If installed with rancher is associated to the rancher version from what I know.

**Comment by brandond** [comment]
I'm confused why we have SRIOV images in our Multus tarball, if they are no longer bundled with Multus or in any way tied to the Multus chart version.

I feel like we should either remove these from the multus tarball, or call out in the release notes what version of the SRIOV chart the images are meant to be used with.

**Comment by rbrtbnfgl** [comment]
@thomasferrandiz has more knowledge of SRIOV

**Comment by thomasferrandiz** [comment]
@brandond I think you're right and the images were added in the multus tarball because at first sriov was supposed to be bundled and installed with multus.
Since the sriov chart had to be moved in Rancher later, we just ended up in a situation where we hope that the version of the images in the airgap tarball matches the version used by the chart in the Rancher repo.

We could add the versions to the release notes to help users understand if they have the right versions.
Is it done only through the PR description?

**Comment by brandond** [comment]
This needs to go deeper than just PR titles or descriptions. 

I think we should do one of two things:
1. - Remove the SRIOV images from the multus tarball, since multus and sriov are no longer tied together.
2. - Work with the QA and release teams to figure out how to best indicate which version of the sriov chart the multus airgap tarball is meant to be used with, and add this to the component version table in the release notes.
    - Add CI checks to ensure that the images are correct for the indicated chart version - like we have for other chart images.

**Comment by thomasferrandiz** [comment]
As discussed, it is simpler to just remove the sriov images from the airgap tarball: https://github.com/rancher/rke2/pull/6747

**Pull request closed without merging**
