### PR TITLE
Private registry enhancements

### PR DESCRIPTION
**Pull request by brandond**
#### Proposed Changes ####

* Properly handle URI path in registry endpoint override
* Don't inject docker.io as global.systemDefaultRegistry by default
* Add support for repository rewrites (containerd/containerd#5171)

Registry rewrite support needs documentation

#### Types of Changes ####

* Private registry support

#### Verification ####

Some of these will require a specially configured private registry to test

* Do not set --system-default-registry, and customize HelmChart image repository as described in #849; note that HelmChart deploys successfully and uses correct registry.
* Use private registry with api not at /v2 - `https://registry.lan/prefix/v2` for example - as described in #853; note that runtime image pull succeeds.
* Use private registry with images mirrored at modified path - `registry.lan/rancher-mirror` for example - as described in #741; note that runtime image pull succeeds.

```yaml
mirrors:
  docker.io:
    endpoint:
      - https://registry.lan/local/v2/
    rewrite:
      "^rancher/(.*)": "rancher-mirror/$1"
configs:
  registry.lan:
    tls:
      insecure_skip_verify: true
``` 

#### Linked Issues ####

#741
#768
#849 
#853

### CODE REVIEW

**Review by briandowns — APPROVED** [review]
LGTM

**Review by erikwilson — APPROVED** [review]

**Comment by Martin-Weiss** [comment]
Just tried to test this with v1.20.5-alpha1+rke2r2 but somehow the runtime image does not get downloaded.
I am not sure how to configure the registries.yaml properly.. basically I want to rewrite

docker.io/rancher/* to registry01.suse:5000/rke-test/docker.io/rancher/*

or even better

docker.io/* to registry01.suse:5000/rke-test/docker.io/*

As all the images from docker.io are replicated to  registry01.suse:5000/rke-test/docker.io/*

I.e. the rke2-runtime image exists as registry01.suse:5000/rke-test/docker.io/rancher/rke2-runtime:v1.20.5-alpha1-rke2r2

But somehow this config does not work:

```
mirrors:
  docker.io:
    endpoint:
      - "https://registry01.suse:5000/v2/"
    rewrite:
      "(.*)": "rke-test/docker.io/$1"
```

```
Apr 13 16:10:19 rke-test-master-01 systemd[1]: rke2-server.service: Service RestartSec=5s expired, scheduling restart.
Apr 13 16:10:19 rke-test-master-01 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Apr 13 16:10:19 rke-test-master-01 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Apr 13 16:10:19 rke-test-master-01 systemd[1]: Started Rancher Kubernetes Engine v2 (server).
Apr 13 16:10:19 rke-test-master-01 rke2[5622]: time="2021-04-13T16:10:19+02:00" level=debug msg="No local image available for index.docker.io/rancher/rke2-runtime:v1.20.5-alpha1-rke2r2: directory /var/lib/rancher/rke2/agent/images does not exist"
Apr 13 16:10:19 rke-test-master-01 rke2[5622]: time="2021-04-13T16:10:19+02:00" level=debug msg="No local image available for index.docker.io/rancher/rke2-runtime:v1.20.5-alpha1-rke2r2: directory /var/lib/rancher/rke2/agent/images does not exist"
Apr 13 16:10:19 rke-test-master-01 rke2[5622]: time="2021-04-13T16:10:19+02:00" level=info msg="Using registry config file at /etc/rancher/rke2/registries.yaml"
Apr 13 16:10:19 rke-test-master-01 rke2[5622]: time="2021-04-13T16:10:19+02:00" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.20.5-alpha1-rke2r2"
Apr 13 16:10:19 rke-test-master-01 rke2[5622]: time="2021-04-13T16:10:19+02:00" level=fatal msg="failed to get runtime image rancher/rke2-runtime:v1.20.5-alpha1-rke2r2: GET https://registry01.suse:5000/v2/rke-test/docker.io/rancher/rke2-runtime/manifests/v1.20.5-alpha1-rke2r2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:rke-test/docker.io/rancher/rke2-runtime Type:repository]]"
Apr 13 16:10:19 rke-test-master-01 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 16:10:19 rke-test-master-01 systemd[1]: rke2-server.service: Unit entered failed state.
Apr 13 16:10:19 rke-test-master-01 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
```

Could you help me with the info how I should configure registries.yaml?

**Comment by brandond** [comment]
@Martin-Weiss https://github.com/rancher/rke2/issues/871

**Comment by aslafy-z** [comment]
Any chance this gets backported to rke 1.x?

**Comment by brandond** [comment]
@aslafy-z highly unlikely since RKE1 uses docker and this is all based on features built in to containerd.

**Comment by aslafy-z** [comment]
Hm, sorry I mistaken between our rke deployment and k3s. Is this planned to be integrated into k3s in some way? Thanks!

**Comment by brandond** [comment]
K3s already supports registries.yaml, and the bits changed here are specific to the RKE2 runtime image bootstrap which K3s does not have. What specifically are you looking for?

**Comment by marshallford** [comment]
I'm excited to see this land in `v1.20.6+rke2r1` 🎉 

Would it be possible to add a rewrite example to the [private registry methods section](https://docs.rke2.io/install/airgap/#private-registry-method) of the air-gap docs? Specifically for the case where the rke2 container images specified in `rke2-images.linux-<arch>.txt` are pushed to `some.registry.lan/foo/bar/baz/`, but the entirety of `docker.io` **is not** mirrored to the nested registry namespace. I'm unclear on if I should be setting `system-default-registry`, using `rewrite` somehow in `registries.yaml`, or perhaps both?

Thanks!

**Pull request merged**
